<?xml version="1.0" encoding="utf-8"?><Database Name="STUDENT_nan.cao@kahosl.be" Class="KotAtGentDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PBAICTSQLFARM02.acad.kahosl.be;Initial Catalog=STUDENT_nan.cao@kahosl.be;Persist Security Info=True;User ID=STUDENT_SQLHigh_nan.cao@kahosl.be" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="STUDENT_nan_cao_kahosl_beConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KotAtGent_Type" Member="KotAtGent_Types">
    <Type Name="KotAtGent_Type">
      <Column Name="Type" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="KotAtGent_Type_KotAtGent_Room" Member="KotAtGent_Rooms" ThisKey="Type" OtherKey="Type" Type="KotAtGent_Room" />
    </Type>
  </Table>
  <Table Name="dbo.KotAtGent_UserReservation" Member="KotAtGent_UserReservations">
    <Type Name="KotAtGent_UserReservation">
      <Column Name="ReserveDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KotId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KotAtGent_Users" Member="KotAtGent_Users">
    <Type Name="KotAtGent_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="Binary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.KotAtGent_Zone" Member="KotAtGent_Zones">
    <Type Name="KotAtGent_Zone">
      <Column Name="Zone" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="KotAtGent_Zone_KotAtGent_Room" Member="KotAtGent_Rooms" ThisKey="Zone" OtherKey="Zone" Type="KotAtGent_Room" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Membership" Member="webpages_Memberships">
    <Type Name="webpages_Membership">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPasswordFailureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordFailuresSinceLastSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordVerificationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PasswordVerificationTokenExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KotAtGent_Rooms" Member="KotAtGent_Rooms">
    <Type Name="KotAtGent_Room">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Zone" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Adres" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Eigenaar_naam" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Eigenaar_telefoon" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Eigenaar_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Kamers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Min_prijs" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Max_prijs" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Lat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Long" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Beschrijving" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Datum" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Foto1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Foto2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Foto3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="KotAtGent_Type_KotAtGent_Room" Member="KotAtGent_Type" ThisKey="Type" OtherKey="Type" Type="KotAtGent_Type" IsForeignKey="true" />
      <Association Name="KotAtGent_Zone_KotAtGent_Room" Member="KotAtGent_Zone" ThisKey="Zone" OtherKey="Zone" Type="KotAtGent_Zone" IsForeignKey="true" />
    </Type>
  </Table>
</Database>